### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by CGSGAU3** [tapika/TestCppReflect#1]
How can I make static array (ex. int a[100]) reflectable?

**Comment by tapika** [comment]
My test application actively uses macros, which is something that was relevant 5 years ago, but anymore.

I believe better approach would be to use Microsoft provided IFC SDK , see [link](https://github.com/microsoft/ifc-spec/issues/49#issuecomment-1747026903). But I haven't yet tried that one by myself.

Let's start maybe from IFC SDK, and if it does not work for you - maybe you can raise same ticket again to this repo ? :)

**Comment by CGSGAU3** [comment]
I wanted to do such a thing without using big libraries or SDK. Only hardcode :))
